### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by davidobrien1985** [ndrewtl/airspace-jekyll#22]
Hi,

what's the recommended way to get the contact form to actually send the message somewhere?

I couldn't find anywhere in the code anything where I can add a recipient email address or anything.

Thanks,
David

**Comment by davidobrien1985** [comment]
Never mind, I missed the part where I just need to add a 

```
action="https://getsimpleform.com/messages?form_api_token=<form_api_token>" method="post"
```

to the `<form>` section. Of course only if you want to use getsimpleform.

**Comment by dsobrien** [comment]
Hi, I am also having the same problem. Can you give me an example of the contact file with the action? I want to have formspree function but with the themes design.

**Comment by ndrewtl** [comment]
Hi! Given that this is just a template or front-end for a website, it does not provide server functionality to send email. If you want this, you must buy it from your host, or (much easier) use a third-party tool. This is recommended unless you _really_ know what you're doing.

For your use-case, your best bet is to simply follow the directions from your provider. I recommend [formspree](https://formspree.io/) for down-and-dirty form emails and [mailchimp](https://mailchimp.com/) if you want a glossier, more professional email.

I'm not an expert on this topic, but the gist of it is copying the HTML widget that formspree provides on their homepage. This template is just a demonstration of html styles, so I'm not going to hardcode in a formspree configuration, but copy-pasting in their example form should work. Edit element classes as necessary to make the form render correctly, and you should be fine.
