### ISSUE TITLE
Instructions to run the project in localhost

### ISSUE THREAD

**Issue by vikaskyadav** [ndrewtl/airspace-jekyll#24]
Can anybody list down the installations and steps to build and run the project in localhost?

**Comment by ndrewtl** [comment]
### Make sure you have Ruby

First, make sure you have [Ruby](https://www.ruby-lang.org/en/) installed. You can confirm this by running `ruby -v` on the command line:

```sh
$ ruby -v
ruby [version number] (date) [your platform]
```

If you get something like `"Error, command not found"` visit the link above and install Ruby for your platform.


### Make sure you have Jekyll

Next, make sure you have [Jekyll](https://jekyllrb.com/) installed. Just like above, run `jekyll -v` on the command line:

```sh
$ jekyll -v
jekyll [version number]
```
If you get `"Error, command not found"` run `gem install jekyll` to install it using RubyGems.

### Run this repository
Clone the repository, and `cd` into it:
```sh
$ git clone https://github.com/ndrewtl/airspace-jekyll.git
$ cd airspace-jekyll
```

Install Dependencies
```sh
$ bundle install
```

And run the server:
```sh
$ jekyll serve
```

Hope this works!

@ndrewtl
