### ISSUE TITLE
Unable to install as instructed

### ISSUE THREAD

**Issue by JetForMe** [ndrewtl/airspace-jekyll#33]
Using the master readme instructions for installing, I get the following error:

```
$ bundle install
fatal: not a git repository (or any of the parent directories): .git
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.12)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.12)' in any of the relevant sources:
  the local ruby installation
```

Updating `airspace-jekyll.gemspec` to use `~> 2.0` for bundler, I'm able to install, but upon serving the page I get a `404 '/' not found.`

**Comment by ndrewtl** [comment]
Have you tried visiting `/airspace-jekyll`? I don't think I have it set to serve anything on `/` by default.

**Comment by ndrewtl** [comment]
I've updated the dependencies so bundler should work now. I'm closing this issue. Feel free to reopen if you run into any issues.

**Comment by JetForMe** [comment]
Works! I also figured out the baseURL thing. Thanks!
