### ISSUE TITLE
Would love to see our license in your theme.

### ISSUE THREAD

**Issue by mehedi-sharif** [ndrewtl/airspace-jekyll#40]
Hello Andrew,
Thanks for making our themes in jekyll. It's an achievement of our team. I saw huge people love airspace jekyll theme version and build their website. Somehow they missed the license . It would be great if you add our license page (http://themefisher.com/license) in your read me file and also add our product page https://themefisher.com/products/airspace-free-bootstrap-website-template/ . So that users can get a clear idea. 
Thanks again for your support . I have few plans also.How can I connect with you ?

**Comment by ndrewtl** [comment]
Unfortunately, I'm currently working and can't contribute to open-source. But if you'd like to submit a PR I'd be happy to review. I'm not able to maintain this project super regularly, and I might archive it soon.

**Comment by mehedi-sharif** [comment]
@ndrewtl  I made an pull request . Please add in the repo .
